/**
 * Git pre-commit hook manager.
 *
 * Installs a self-contained Node.js hook into .git/hooks/pre-commit that scans
 * staged diff lines for credentials using the same patterns as the extension.
 * No Python or external dependencies required — the patterns are embedded.
 */

import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";

const HOOK_MARKER = "// flcn-sec-managed-hook";
const HOOK_VERSION = "1";

// ---------------------------------------------------------------------------
// Hook script — embedded JS, runs via `node` in pre-commit context.
// Patterns are duplicated from detector.ts so the hook has zero runtime deps.
// ---------------------------------------------------------------------------

function buildHookScript(): string {
  return `#!/usr/bin/env node
${HOOK_MARKER} v${HOOK_VERSION} — Auto-generated by FLCN Sec VS Code extension. Do not edit manually.
"use strict";

const { execSync } = require("child_process");

// --- Credential patterns (mirrors flcn-sec/vscode/src/detector.ts) ----------
const PATTERNS = [
  { kind: "Anthropic API Key",           re: /\\bsk-ant-[A-Za-z0-9_\\-]{40,}/g },
  { kind: "OpenAI API Key",              re: /\\bsk-(?!ant-)[A-Za-z0-9]{20,}/g },
  { kind: "AWS Access Key ID",           re: /\\bAKIA[0-9A-Z]{16}\\b/g },
  { kind: "AWS Secret Access Key",       re: /aws_secret_access_key\\s*[:=]\\s*['"]?([A-Za-z0-9\\/+=]{39,41})['"]?/gi, group: 1 },
  { kind: "GitHub Token",                re: /\\bgh[pousr]_[A-Za-z0-9]{36,}\\b/g },
  { kind: "Slack Token",                 re: /\\bxox[abprs]-[A-Za-z0-9\\-]{10,}\\b/g },
  { kind: "Stripe Secret Key",           re: /\\b(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{16,}\\b/g },
  { kind: "Google API Key",              re: /\\bAIza[0-9A-Za-z_\\-]{35}\\b/g },
  { kind: "JSON Web Token",              re: /\\beyJ[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\b/g },
  { kind: "PEM Private Key",             re: /-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----/g },
  { kind: "GCP Service Account",         re: /"type"\\s*:\\s*"service_account"/g, co: /"private_key"/ },
  { kind: "HuggingFace Token",           re: /\\bhf_[A-Za-z0-9]{34,}\\b/g },
  { kind: "npm Token",                   re: /\\bnpm_[A-Za-z0-9]{36,}\\b/g },
  { kind: "Docker Hub PAT",              re: /\\bdckr_pat_[A-Za-z0-9_\\-]{43,}\\b/g },
  { kind: "SendGrid API Key",            re: /\\bSG\\.[A-Za-z0-9_\\-]{22}\\.[A-Za-z0-9_\\-]{43}\\b/g },
  { kind: "DigitalOcean Token",          re: /\\bdop_v1_[A-Za-z0-9]{64}\\b/g },
  { kind: "Databricks Token",            re: /\\bdapi[a-z0-9]{32}\\b/g },
  { kind: "Azure Storage Key",           re: /AccountKey=([A-Za-z0-9+\\/=]{86,88})/g, group: 1 },
  { kind: "MongoDB Connection String",   re: /mongodb(?:\\+srv)?:\\/\\/[^:\\s]+:([^@\\s]{8,})@/g, group: 1 },
  { kind: "Env-style Secret Assignment", re: /^(?:export\\s+)?[A-Z][A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD|PASSWD|PWD|CREDENTIAL)[A-Z0-9_]*\\s*=\\s*(\\S{12,})/gim, group: 1 },
];

// ANSI helpers
const R = "\\x1b[0m";
const bold = s => \`\\x1b[1m\${s}\${R}\`;
const red = s => \`\\x1b[31m\${s}\${R}\`;
const yellow = s => \`\\x1b[33m\${s}\${R}\`;
const cyan = s => \`\\x1b[36m\${s}\${R}\`;
const dim = s => \`\\x1b[2m\${s}\${R}\`;
const bgRed = s => \`\\x1b[41m\\x1b[97m\${s}\${R}\`;

function preview(s) {
  if (!s) return "";
  const v = String(s);
  if (v.length <= 8) return "*".repeat(v.length);
  return v.slice(0, 4) + "…" + v.slice(-4);
}

function scan(text, fullText) {
  const findings = [];
  for (const def of PATTERNS) {
    if (def.co && !def.co.test(fullText ?? text)) continue;
    const re = new RegExp(def.re.source, def.re.flags.includes("g") ? def.re.flags : def.re.flags + "g");
    let m;
    while ((m = re.exec(text)) !== null) {
      const val = def.group ? (m[def.group] ?? m[0]) : m[0];
      if (!val || val.startsWith("[REDACTED:")) continue;
      findings.push({ kind: def.kind, value: val });
    }
  }
  return findings;
}

// Get staged file paths
let stagedFiles = [];
try {
  stagedFiles = execSync("git diff --cached --name-only", { encoding: "utf8" })
    .split("\\n").map(s => s.trim()).filter(Boolean);
} catch (e) {
  process.exit(0);
}

// Sensitive path heuristic
const SENSITIVE_PATH_RE = /(\\.env(\\.\\w+)?|credentials|id_rsa|id_ed25519|id_ecdsa|\\.pem|\\.key|service.account.*\\.json|firebase.adminsdk.*\\.json)$/i;

// Build a map of file -> findings
const byFile = new Map();

for (const file of stagedFiles) {
  const fileFindings = [];

  if (SENSITIVE_PATH_RE.test(file)) {
    fileFindings.push({ kind: "Sensitive file path", display: file });
  }

  let fileDiff = "";
  try {
    fileDiff = execSync(\`git diff --cached --unified=0 -- "\${file}"\`, { encoding: "utf8" });
  } catch {}
  const addedLines = fileDiff.split("\\n")
    .filter(l => l.startsWith("+") && !l.startsWith("+++"))
    .map(l => l.slice(1))
    .join("\\n");
  for (const f of scan(addedLines, fileDiff)) {
    fileFindings.push(f);
  }

  if (fileFindings.length > 0) byFile.set(file, fileFindings);
}

if (byFile.size === 0) process.exit(0);

const W = 60;
const line = "─".repeat(W);
const e = s => process.stderr.write(s);

e("\\n");
e(bold(red(\`  ╔\${line}╗\\n\`)));
e(bold(red(\`  ║\${bgRed("  🔒 FLCN Sec — COMMIT BLOCKED  ").padEnd(W + 9)}║\\n\`)));
e(bold(red(\`  ║  \${red(bold(\`\${byFile.size} file(s) contain credentials. Remove before committing.\`)).padEnd(W + 8)}║\\n\`)));
e(bold(red(\`  ╚\${line}╝\\n\`)));
e("\\n");

for (const [file, findings] of byFile) {
  e(\`  \${bold(yellow("┌─ 📄 " + file))}\\n\`);
  findings.forEach((f, i) => {
    const isLast = i === findings.length - 1;
    const prefix = isLast ? "└─" : "├─";
    const kind = cyan(\`[\${f.kind}]\`);
    const val = dim(f.display ?? preview(f.value));
    e(\`  \${prefix}  \${kind}  \${val}\\n\`);
  });
  e("\\n");
}

e(dim(\`  To skip this check (DANGEROUS): git commit --no-verify\\n\`));
e("\\n");
process.exit(1);
`;
}

// ---------------------------------------------------------------------------
// Exported API
// ---------------------------------------------------------------------------

export async function installGitHook(root: string, output: vscode.OutputChannel): Promise<boolean> {
  const hooksDir = path.join(root, ".git", "hooks");
  if (!fs.existsSync(hooksDir)) return false;

  const hookPath = path.join(hooksDir, "pre-commit");

  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, "utf8");
    if (existing.includes(HOOK_MARKER)) {
      // Already managed by us — overwrite to update
      fs.writeFileSync(hookPath, buildHookScript(), "utf8");
      fs.chmodSync(hookPath, 0o755);
      output.appendLine(`[flcn-sec] Updated pre-commit hook: ${hookPath}`);
      return true;
    }
    // Foreign hook — chain ours in
    const chained = chainHook(existing, hookPath, output);
    if (!chained) return false;
    return true;
  }

  fs.writeFileSync(hookPath, buildHookScript(), "utf8");
  fs.chmodSync(hookPath, 0o755);
  output.appendLine(`[flcn-sec] Installed pre-commit hook: ${hookPath}`);
  return true;
}

export function uninstallGitHook(root: string, output: vscode.OutputChannel): boolean {
  const hookPath = path.join(root, ".git", "hooks", "pre-commit");
  if (!fs.existsSync(hookPath)) return false;

  const content = fs.readFileSync(hookPath, "utf8");

  if (!content.includes(HOOK_MARKER)) {
    output.appendLine(`[flcn-sec] pre-commit hook not managed by flcn-sec — skipping.`);
    return false;
  }

  if (content.trim().split("\n").every(l => l.startsWith("#") || buildHookScript().includes(l))) {
    // Entire hook is ours — remove it
    fs.unlinkSync(hookPath);
    output.appendLine(`[flcn-sec] Removed pre-commit hook: ${hookPath}`);
    return true;
  }

  // Chained hook — strip our section
  const stripped = content.replace(/\n# --- flcn-sec begin ---[\s\S]*?# --- flcn-sec end ---\n/g, "");
  fs.writeFileSync(hookPath, stripped, "utf8");
  output.appendLine(`[flcn-sec] Removed flcn-sec section from pre-commit hook: ${hookPath}`);
  return true;
}

export function isHookInstalled(root: string): boolean {
  const hookPath = path.join(root, ".git", "hooks", "pre-commit");
  if (!fs.existsSync(hookPath)) return false;
  return fs.readFileSync(hookPath, "utf8").includes(HOOK_MARKER);
}

export function getGitRoot(workspaceFolders: readonly vscode.WorkspaceFolder[] | undefined): string | undefined {
  if (!workspaceFolders?.length) return undefined;
  for (const folder of workspaceFolders) {
    const candidate = path.join(folder.uri.fsPath, ".git");
    if (fs.existsSync(candidate) && fs.statSync(candidate).isDirectory()) {
      return folder.uri.fsPath;
    }
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

function chainHook(existing: string, hookPath: string, output: vscode.OutputChannel): boolean {
  // Inject our hook as a sourced Node call at the end of the existing script.
  // We write a tiny side-file so we don't corrupt the existing interpreter line.
  const dir = path.dirname(hookPath);
  const sidePath = path.join(dir, "pre-commit.flcn-sec");
  fs.writeFileSync(sidePath, buildHookScript(), "utf8");
  fs.chmodSync(sidePath, 0o755);

  const injection = `\n# --- flcn-sec begin ---\n${HOOK_MARKER} v${HOOK_VERSION}\nnode "${sidePath}" || exit 1\n# --- flcn-sec end ---\n`;
  fs.writeFileSync(hookPath, existing + injection, "utf8");
  output.appendLine(`[flcn-sec] Chained pre-commit hook alongside existing hook: ${hookPath}`);
  return true;
}
